version: '3'
services:
  # 1. 数据库 MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_lark
    environment:
      MYSQL_ROOT_PASSWORD: root  #
      MYSQL_DATABASE: lark_db    # 数据库名
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 2. 缓存 Redis
  redis:
    image: redis:7.0
    container_name: lark_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # 开启持久化
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_lark
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_lark
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

# 启动:终端输入：docker exec -it mysql_lark mysql -uroot -proot lark_db
# 启动redis:docker-compose up -d redis
# 清空redis缓存：docker exec -it lark_redis redis-cli FLUSHALL
# 启动mysql:docker exec -it mysql_lark mysql -uroot -proot lark_db